trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
      - RELEASE_NOTES.md

pr:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
      - RELEASE_NOTES.md

jobs:

- template: build-template.yml
  parameters:
    name: Windows
    vm: 'vs2017-win2016'

- template: build-template.yml
  parameters:
    name: Linux
    vm: 'ubuntu-16.04'

- template: build-template.yml
  parameters:
    name: MacOS
    vm: 'macOS-10.13'